Test_Employee/Models/Department.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Test_Employee.Models
{
    [Table ("usrDepartment")]
    public class Department
    {
        public int id { get; set; }
        public string Name { get; set; }
    }
}

Test_Employee/Models/Employee.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Test_Employee.Models
{
    [Table("tblEmployee")]
    public class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int Department { get; set; }

    }
}

Test_Employee/Models/EmployeeContext.cs
using System.Data.Entity;

namespace Test_Employee.Models
{
    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> _Employees { get; set; }
        public DbSet<Department> _Departments { get; set; }

    }
}

Test_Employee/Controllers/DepartmentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Test_Employee.Models;

namespace Test_Employee.Controllers
{
    public class DepartmentController : Controller
    { 
        public ActionResult Index()
        {
            EmployeeContext _employeeContext = new EmployeeContext();
            List<Department> _Departments=  _employeeContext._Departments.ToList(); 
            return View(_Departments);
        }
    }
}

Test_Employee/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Test_Employee.Models;

namespace Test_Employee.Controllers
{
    public class EmployeeController : Controller
    {
        public ActionResult Index( int DepartmentID)
        {
            EmployeeContext _EmployeeContext = new EmployeeContext();
            List<Employee> _EmployeeS = _EmployeeContext._Employees.Where(Emp => Emp.Department == DepartmentID ).ToList();
            return View(_EmployeeS);
        }


        public ActionResult Details( int ID )
        {
            EmployeeContext _EmployeeContext = new EmployeeContext();
            Employee _Employee = _EmployeeContext._Employees.Single(Empl => Empl.EmployeeID == ID);

            return View(_Employee);
        }
    }
}

Test_Employee/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test_Employee.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
            
        }
    }
}

Test_Employee/Views/Department/Index.cshtml
@model IEnumerable<Test_Employee.Models.Department>
@using Test_Employee.Models
@{
    ViewBag.Title = "Department Details";
}

<div style="font-family:Arial">
    <h2>Department Details </h2>
    <ul>
        @foreach (Department item in Model)
        {
            <li>
                @Html.ActionLink(item.Name, "Index", "Employee", new { Departmentid = item.id }, null);
            </li>
        }

    </ul>
</div>

Test_Employee/Views/Employee/Details.cshtml
@{
    ViewBag.Title = "Employee Details";
}

<h2> Employee Details</h2>
<table style="font-family:Arial">
    <tr>
        <td>
            Employee ID :
        </td>
        <td>
            @Model.EmployeeID
        </td>
    </tr>
    <tr>
        <td>
            Employee Name :
        </td>
        <td>
            @Model.Name
        </td>
    </tr>
    <tr>
        <td>
            Gender :
        </td>
        <td>
            @Model.Gender
        </td>
    </tr>
    <tr>
        <td>
            City :
        </td>
        <td>
            @Model.City
        </td>
    </tr>
</table>

 
 @Html.ActionLink("Back to List ", "Index",  new { Departmentid = Model.Department });

Test_Employee/Views/Employee/Index.cshtml
@model IEnumerable<Test_Employee.Models.Employee>
@using Test_Employee.Models  
 @{
        ViewBag.Title = "Employee List";
 }

<div style="font-family:Arial">
    <h2>Employee List</h2>
    <ul>
        @foreach (Employee item in Model)
        {
             <li>
            @Html.ActionLink(item.Name, "Details", new { id = item.EmployeeID });
             </li>
        }
        @Html.ActionLink("Back to List ", "Index", "Department" );
    </ul>
</div>

Test_Employee/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Test_Employee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>